spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java1904?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#logging:
 # file: d://log//all.log